[workspace]
name = "foo-portable"
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
python = "3.10.*"
pip = "*"
git = "*"   # strongly recommended for git deps on Windows

[pypi-options]
index-url = "https://download.pytorch.org/whl/test/cu128"
extra-index-urls = [
  "https://download.pytorch.org/whl/nightly/cu128",
  "https://pypi.org/simple",
]
index-strategy = "unsafe-best-match"

[pypi-dependencies]
world_engine = { git = "https://github.com/Wayfarer-Labs/world_engine.git" }

[tasks]
client = "python src/client.py"
